import type { TreatmentPlan, TreatmentPlanListItem } from '../types'

export const STATUS_CONFIG = {
	DRAFT: {
		label: 'Draft',
		className: 'bg-slate-50 text-slate-700 border-slate-200',
	},
	APPROVED: {
		label: 'Approved',
		className: 'bg-green-50 text-green-700 border-green-200',
	},
	REJECTED: {
		label: 'Rejected',
		className: 'bg-red-50 text-red-700 border-red-200',
	},
} as const

export const RISK_CONFIG = {
	LOW: {
		label: 'Low Risk',
		className: 'bg-green-50 text-green-700 border-green-200',
	},
	MEDIUM: {
		label: 'Medium Risk',
		className: 'bg-yellow-50 text-yellow-700 border-yellow-200',
	},
	HIGH: {
		label: 'High Risk',
		className: 'bg-red-50 text-red-700 border-red-200',
	},
} as const

export const SEVERITY_CONFIG = {
	Mild: {
		label: 'Mild',
		className: 'bg-blue-50 text-blue-700 border-blue-200',
	},
	Moderate: {
		label: 'Moderate',
		className: 'bg-yellow-50 text-yellow-700 border-yellow-200',
	},
	Severe: {
		label: 'Severe',
		className: 'bg-red-50 text-red-700 border-red-200',
	},
} as const

export const MOCK_TREATMENT_PLANS: TreatmentPlan[] = [
	{
		id: 'plan-1',
		patientId: 'patient-1',
		patient: {
			id: 'patient-1',
			name: 'John Doe',
			dateOfBirth: '1979-03-15',
			gender: 'MALE',
			allergies: ['Penicillin'],
			chronicConditions: ['Hypertension', 'Type 2 Diabetes'],
		},
		doctorId: 'doctor-1',
		chiefComplaint: 'Persistent headaches and elevated blood pressure',
		currentSymptoms: 'Headaches for 2 weeks, dizziness, occasional blurred vision',
		vitalSigns: {
			bloodPressureSystolic: 158,
			bloodPressureDiastolic: 95,
			heartRate: 82,
			temperature: 98.6,
			respiratoryRate: 16,
			oxygenSaturation: 98,
		},
		physicalExamNotes: 'Patient appears well-nourished. No acute distress. Cardiovascular exam reveals regular rhythm, no murmurs.',
		aiRecommendations: {
			medications: [
				{
					name: 'Lisinopril',
					genericName: 'Lisinopril',
					dosage: '10mg',
					frequency: 'Once daily',
					duration: '30 days',
					route: 'Oral',
					instructions: 'Take in the morning with or without food',
					confidenceScore: 92,
				},
				{
					name: 'Amlodipine',
					genericName: 'Amlodipine besylate',
					dosage: '5mg',
					frequency: 'Once daily',
					duration: '30 days',
					route: 'Oral',
					instructions: 'Take at the same time each day',
					confidenceScore: 88,
				},
			],
			rationale: 'Given the patient history of hypertension and current elevated BP readings, a combination of ACE inhibitor and calcium channel blocker is recommended for optimal blood pressure control.',
			recommendations: [
				'Monitor blood pressure daily',
				'Reduce sodium intake',
				'Follow up in 2 weeks',
			],
		},
		finalPlan: {
			medications: [
				{
					name: 'Lisinopril',
					genericName: 'Lisinopril',
					dosage: '10mg',
					frequency: 'Once daily',
					duration: '30 days',
					route: 'Oral',
					instructions: 'Take in the morning with or without food',
				},
			],
			notes: 'Starting with monotherapy. Will reassess in 2 weeks.',
		},
		riskLevel: 'MEDIUM',
		riskFactors: ['Elevated blood pressure', 'History of diabetes', 'Age > 40'],
		riskJustification: 'Patient has multiple cardiovascular risk factors requiring careful monitoring.',
		drugInteractions: [],
		contraindications: [],
		alternatives: [
			{
				medications: [
					{
						name: 'Losartan',
						dosage: '50mg',
						frequency: 'Once daily',
						duration: '30 days',
						route: 'Oral',
					},
				],
				rationale: 'ARB alternative if ACE inhibitor causes cough',
				riskLevel: 'LOW',
			},
		],
		status: 'APPROVED',
		wasModified: true,
		modificationNotes: 'Reduced to monotherapy based on patient preference',
		createdAt: '2024-12-01T10:30:00Z',
		updatedAt: '2024-12-02T14:15:00Z',
		approvedAt: '2024-12-02T14:15:00Z',
	},
	{
		id: 'plan-2',
		patientId: 'patient-2',
		patient: {
			id: 'patient-2',
			name: 'Jane Smith',
			dateOfBirth: '1992-07-22',
			gender: 'FEMALE',
			allergies: ['Sulfa drugs'],
			chronicConditions: ['Type 2 Diabetes'],
		},
		doctorId: 'doctor-1',
		chiefComplaint: 'Poor glycemic control despite current medication',
		currentSymptoms: 'Fatigue, increased thirst, frequent urination, HbA1c 8.5%',
		vitalSigns: {
			bloodPressureSystolic: 128,
			bloodPressureDiastolic: 82,
			heartRate: 76,
			temperature: 98.4,
		},
		aiRecommendations: {
			medications: [
				{
					name: 'Metformin',
					dosage: '1000mg',
					frequency: 'Twice daily',
					duration: '90 days',
					route: 'Oral',
					instructions: 'Take with meals',
					confidenceScore: 95,
				},
				{
					name: 'Empagliflozin',
					dosage: '10mg',
					frequency: 'Once daily',
					duration: '90 days',
					route: 'Oral',
					instructions: 'Take in the morning',
					confidenceScore: 87,
				},
			],
			rationale: 'Addition of SGLT2 inhibitor to improve glycemic control and provide cardiovascular protection.',
			recommendations: [
				'Monitor blood glucose regularly',
				'Check HbA1c in 3 months',
				'Watch for signs of UTI',
			],
		},
		riskLevel: 'LOW',
		riskFactors: ['Suboptimal diabetes control'],
		drugInteractions: [],
		contraindications: [],
		alternatives: [],
		status: 'DRAFT',
		wasModified: false,
		createdAt: '2024-12-03T09:00:00Z',
		updatedAt: '2024-12-03T09:00:00Z',
	},
	{
		id: 'plan-3',
		patientId: 'patient-3',
		patient: {
			id: 'patient-3',
			name: 'Robert Johnson',
			dateOfBirth: '1966-11-08',
			gender: 'MALE',
			allergies: [],
			chronicConditions: ['Coronary Artery Disease', 'Hyperlipidemia'],
		},
		doctorId: 'doctor-1',
		chiefComplaint: 'Chest discomfort with exertion',
		currentSymptoms: 'Chest tightness during physical activity, shortness of breath, resolved with rest',
		vitalSigns: {
			bloodPressureSystolic: 142,
			bloodPressureDiastolic: 88,
			heartRate: 72,
			oxygenSaturation: 96,
		},
		physicalExamNotes: 'S1, S2 normal. No S3 or S4. Lungs clear bilaterally.',
		aiRecommendations: {
			medications: [
				{
					name: 'Aspirin',
					dosage: '81mg',
					frequency: 'Once daily',
					duration: 'Ongoing',
					route: 'Oral',
					confidenceScore: 98,
				},
				{
					name: 'Atorvastatin',
					dosage: '40mg',
					frequency: 'Once daily at bedtime',
					duration: 'Ongoing',
					route: 'Oral',
					confidenceScore: 96,
				},
				{
					name: 'Metoprolol succinate',
					dosage: '50mg',
					frequency: 'Once daily',
					duration: 'Ongoing',
					route: 'Oral',
					confidenceScore: 91,
				},
			],
			rationale: 'Standard secondary prevention therapy for CAD with symptom control via beta-blocker.',
			recommendations: [
				'Cardiac stress test recommended',
				'Follow up with cardiology',
				'Lifestyle modifications essential',
			],
		},
		riskLevel: 'HIGH',
		riskFactors: ['Known CAD', 'Age > 55', 'Male gender', 'Hyperlipidemia'],
		riskJustification: 'High cardiovascular risk due to established coronary artery disease.',
		drugInteractions: [
			{
				medication1: 'Aspirin',
				medication2: 'Ibuprofen',
				severity: 'Moderate',
				description: 'NSAIDs may reduce antiplatelet effect of aspirin',
				recommendation: 'Avoid concurrent NSAID use if possible',
			},
		],
		contraindications: [],
		alternatives: [],
		status: 'APPROVED',
		wasModified: false,
		createdAt: '2024-11-28T11:45:00Z',
		updatedAt: '2024-11-29T10:00:00Z',
		approvedAt: '2024-11-29T10:00:00Z',
	},
	{
		id: 'plan-4',
		patientId: 'patient-4',
		patient: {
			id: 'patient-4',
			name: 'Emily Davis',
			dateOfBirth: '1995-04-12',
			gender: 'FEMALE',
			allergies: ['Codeine'],
			chronicConditions: ['Asthma'],
		},
		doctorId: 'doctor-1',
		chiefComplaint: 'Increased asthma symptoms',
		currentSymptoms: 'Wheezing, shortness of breath, nighttime cough, using rescue inhaler 4x/week',
		vitalSigns: {
			bloodPressureSystolic: 118,
			bloodPressureDiastolic: 74,
			heartRate: 78,
			respiratoryRate: 18,
			oxygenSaturation: 97,
		},
		aiRecommendations: {
			medications: [
				{
					name: 'Fluticasone/Salmeterol',
					dosage: '250/50mcg',
					frequency: 'Twice daily',
					duration: '30 days',
					route: 'Inhalation',
					instructions: 'Rinse mouth after use',
					confidenceScore: 94,
				},
				{
					name: 'Albuterol',
					dosage: '90mcg',
					frequency: 'As needed',
					duration: '30 days',
					route: 'Inhalation',
					instructions: 'Use for rescue, max 4-6 puffs daily',
					confidenceScore: 99,
				},
			],
			rationale: 'Step up to combination ICS/LABA therapy given inadequate control with current regimen.',
			recommendations: [
				'Peak flow monitoring',
				'Asthma action plan review',
				'Consider allergy testing',
			],
		},
		riskLevel: 'LOW',
		riskFactors: ['Uncontrolled asthma symptoms'],
		drugInteractions: [],
		contraindications: [],
		alternatives: [],
		status: 'DRAFT',
		wasModified: false,
		createdAt: '2024-12-04T08:30:00Z',
		updatedAt: '2024-12-04T08:30:00Z',
	},
	{
		id: 'plan-5',
		patientId: 'patient-5',
		patient: {
			id: 'patient-5',
			name: 'Michael Chen',
			dateOfBirth: '1988-09-30',
			gender: 'MALE',
			allergies: ['Amoxicillin'],
			chronicConditions: ['Anxiety', 'GERD'],
		},
		doctorId: 'doctor-1',
		chiefComplaint: 'Worsening anxiety and panic attacks',
		currentSymptoms: 'Daily anxiety, 2-3 panic attacks per week, difficulty sleeping, increased heart rate',
		vitalSigns: {
			bloodPressureSystolic: 132,
			bloodPressureDiastolic: 84,
			heartRate: 88,
		},
		aiRecommendations: {
			medications: [
				{
					name: 'Sertraline',
					dosage: '50mg',
					frequency: 'Once daily',
					duration: '90 days',
					route: 'Oral',
					instructions: 'Take in the morning with food',
					confidenceScore: 89,
				},
			],
			rationale: 'SSRI recommended as first-line treatment for anxiety disorder.',
			recommendations: [
				'Consider cognitive behavioral therapy',
				'Sleep hygiene education',
				'Follow up in 4 weeks to assess response',
			],
		},
		riskLevel: 'LOW',
		riskFactors: ['Mental health condition'],
		drugInteractions: [],
		contraindications: [],
		alternatives: [
			{
				medications: [
					{
						name: 'Escitalopram',
						dosage: '10mg',
						frequency: 'Once daily',
						duration: '90 days',
						route: 'Oral',
					},
				],
				rationale: 'Alternative SSRI if sertraline not tolerated',
				riskLevel: 'LOW',
			},
		],
		status: 'APPROVED',
		wasModified: false,
		createdAt: '2024-11-25T14:20:00Z',
		updatedAt: '2024-11-26T09:30:00Z',
		approvedAt: '2024-11-26T09:30:00Z',
	},
]

export const MOCK_TREATMENT_PLAN_LIST: TreatmentPlanListItem[] = MOCK_TREATMENT_PLANS.map(
	(plan) => ({
		id: plan.id,
		patientId: plan.patientId,
		patient: {
			id: plan.patient.id,
			name: plan.patient.name,
		},
		chiefComplaint: plan.chiefComplaint,
		status: plan.status,
		riskLevel: plan.riskLevel,
		createdAt: plan.createdAt,
		updatedAt: plan.updatedAt,
	})
)
